2024-08-20 21:18:40,163 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:18:41,193 - INFO - Websocket connected
2024-08-20 21:18:41,193 - INFO - WebSocket Unified V5 (Auth) connected
2024-08-20 21:18:44,088 - INFO - Placed buy order at 60393.8, Order ID: 1756775203612137216
2024-08-20 21:18:44,107 - INFO - Processing order with ID: 1756775203612137216, Status: New
2024-08-20 21:18:57,344 - INFO - Placed buy order at 60408.8, Order ID: 1756775314736027392
2024-08-20 21:18:57,347 - INFO - Processing order with ID: 1756775314736027392, Status: New
2024-08-20 21:18:58,143 - INFO - Processing order with ID: 1756775203612137216, Status: Cancelled
2024-08-20 21:18:58,143 - INFO - Order cancelled - ID: 1756775203612137216
2024-08-20 21:18:58,145 - INFO - State checkpointed successfully.
2024-08-20 21:19:03,907 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113b0cdd0>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 0.5 seconds...
2024-08-20 21:19:03,918 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:19:04,425 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113b7bf50>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 1.0 seconds...
2024-08-20 21:19:04,426 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:19:05,435 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113ba6010>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 1.5 seconds...
2024-08-20 21:19:05,437 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:19:06,948 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113b0f6d0>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 2.0 seconds...
2024-08-20 21:19:06,951 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:19:08,959 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113ba65d0>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 2.5 seconds...
2024-08-20 21:19:08,962 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:19:11,472 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113bac410>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 3.0 seconds...
2024-08-20 21:19:11,474 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:19:12,932 - INFO - Processing order with ID: 1756775314736027392, Status: Filled
2024-08-20 21:19:12,933 - INFO - Order filled - ID: 1756775314736027392, Side: Buy, Price: 60408.8, Qty: 5e-05
2024-08-20 21:19:14,568 - INFO - Placed sell order at 60423.8, Order ID: 1756775453877868288
2024-08-20 21:19:15,245 - INFO - Placed corresponding sell order with ID: 1756775453877868288
2024-08-20 21:19:17,246 - INFO - Logged filled sell order to database
2024-08-20 21:19:17,247 - INFO - Processing order with ID: 1756775453877868288, Status: New
2024-08-20 21:19:40,613 - INFO - Processing order with ID: 1756775453877868288, Status: Filled
2024-08-20 21:19:40,614 - INFO - Order filled - ID: 1756775453877868288, Side: Sell, Price: 60423.8, Qty: 5e-05
2024-08-20 21:19:41,327 - INFO - Placed buy order at 60423.8, Order ID: 1756775683776059136
2024-08-20 21:19:41,966 - INFO - Processed filled sell order - Pair Profit: -0.005291629999999881
2024-08-20 21:19:42,522 - INFO - Logged filled sell order to database
2024-08-20 21:19:45,174 - INFO - marked sell order 7655b362-316c-4a8f-8e6d-db6aecb42c5f
2024-08-20 21:19:45,174 - INFO - Processing order with ID: 1756775683776059136, Status: Filled
2024-08-20 21:19:45,174 - INFO - Order filled - ID: 1756775683776059136, Side: Buy, Price: 60420.24, Qty: 5e-05
2024-08-20 21:19:46,258 - INFO - Placed sell order at 60438.8, Order ID: 1756775721164084992
2024-08-20 21:19:46,852 - INFO - Placed corresponding sell order with ID: 1756775721164084992
2024-08-20 21:19:48,509 - INFO - Logged filled sell order to database
2024-08-20 21:19:48,510 - INFO - Processing order with ID: 1756775721164084992, Status: New
2024-08-20 21:20:14,455 - INFO - State checkpointed successfully.
2024-08-20 21:20:21,700 - INFO - Placed buy order at 60408.8, Order ID: 1756776022407386880
2024-08-20 21:20:21,708 - INFO - Processing order with ID: 1756776022407386880, Status: New
2024-08-20 21:20:24,774 - INFO - Processing order with ID: 1756775721164084992, Status: Filled
2024-08-20 21:20:24,775 - INFO - Order filled - ID: 1756775721164084992, Side: Sell, Price: 60438.8, Qty: 5e-05
2024-08-20 21:20:26,125 - INFO - Processed filled sell order - Pair Profit: -0.005114952000000006
2024-08-20 21:20:26,613 - INFO - Logged filled sell order to database
2024-08-20 21:20:28,022 - INFO - Placed buy order at 60438.8, Order ID: 1756776075473721088
2024-08-20 21:20:28,676 - INFO - marked sell order c4219eb5-901b-46c0-a8ca-6ab2d3cbefc1
2024-08-20 21:20:28,677 - INFO - Processing order with ID: 1756776075473721088, Status: New
2024-08-20 21:20:39,281 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113b138d0>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 0.5 seconds...
2024-08-20 21:20:39,284 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:20:39,794 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113bae0d0>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 1.0 seconds...
2024-08-20 21:20:39,797 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:20:40,805 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113ba68d0>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 1.5 seconds...
2024-08-20 21:20:40,808 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:20:42,313 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113bb8f50>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 2.0 seconds...
2024-08-20 21:20:42,316 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:20:44,325 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113b20a10>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 2.5 seconds...
2024-08-20 21:20:44,328 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:20:46,839 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113bc19d0>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 3.0 seconds...
2024-08-20 21:20:46,843 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:20:49,854 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113ba6450>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 3.5 seconds...
2024-08-20 21:20:49,858 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:20:53,368 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113bb83d0>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 4.0 seconds...
2024-08-20 21:20:53,372 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:20:57,383 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113bada90>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 4.5 seconds...
2024-08-20 21:20:57,386 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:20:58,681 - ERROR - WebSocket Unified V5 (Auth) (wss://stream.bybit.com/v5/private) encountered error: ping/pong timed out.
2024-08-20 21:21:01,684 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,693 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x113af7ce0>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,718 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,743 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,751 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x1005dc7c0>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,769 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,788 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,795 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x113ace3e0>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,808 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,808 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,816 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x113bc82c0>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,823 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,835 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,843 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x1006613a0>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,855 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,856 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,862 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x113af4fe0>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,875 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,881 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,889 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x113acec00>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,895 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,908 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,915 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x113aceb60>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,915 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113ba6c50>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 5.0 seconds...
2024-08-20 21:21:01,928 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,960 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:21:01,966 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,973 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x113bc8f40>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,973 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,985 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:01,992 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x113bc96c0>: [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:01,999 - INFO - tearing down on exception [Errno 8] nodename nor servname provided, or not known
2024-08-20 21:21:02,005 - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x113acf420>: WebSocket Unified V5 (Auth) (wss://stream.bybit.com/v5/private) connection failed. Too many connection attempts. pybit will no longer try to reconnect.
2024-08-20 21:21:02,005 - ERROR - ping/pong timed out - goodbye
2024-08-20 21:21:06,975 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113baf790>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 5.5 seconds...
2024-08-20 21:21:06,977 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:21:12,487 - ERROR - Error getting index price for BTCUSDT: HTTPSConnectionPool(host='api.bybit.com', port=443): Max retries exceeded with url: /v5/market/tickers?symbol=BTCUSDT&category=spot (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x113ba6710>: Failed to resolve 'api.bybit.com' ([Errno 8] nodename nor servname provided, or not known)")). Retrying in 6.0 seconds...
2024-08-20 21:21:12,490 - ERROR - Error occurred on line     raise ConnectionError(e, request=request)
2024-08-20 21:21:20,223 - INFO - Placed buy order at 60483.8, Order ID: 1756776512285316864
2024-08-20 21:21:25,914 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:26,831 - INFO - Websocket connected
2024-08-20 21:21:26,831 - INFO - WebSocket Unified V5 (Auth) connected
2024-08-20 21:21:26,832 - INFO - Successfully subscribed to WebSocket updates for BTCUSDT
2024-08-20 21:21:26,832 - INFO - Processing missed order updates
2024-08-20 21:21:30,659 - INFO - Processing order with ID: 1756776075473721088, Status: Filled
2024-08-20 21:21:30,659 - INFO - Order filled - ID: 1756776075473721088, Side: Buy, Price: 60438.8, Qty: 5e-05
2024-08-20 21:21:32,356 - INFO - Placed sell order at 60453.8, Order ID: 1756776607311468288
2024-08-20 21:21:33,235 - INFO - Placed corresponding sell order with ID: 1756776607311468288
2024-08-20 21:21:33,949 - INFO - Logged filled sell order to database
2024-08-20 21:21:33,949 - INFO - Processing order with ID: 1756776512285316864, Status: Filled
2024-08-20 21:21:33,949 - INFO - Order filled - ID: 1756776512285316864, Side: Buy, Price: 60483.8, Qty: 5e-05
2024-08-20 21:21:35,666 - INFO - Placed sell order at 60498.8, Order ID: 1756776634666718976
2024-08-20 21:21:36,280 - INFO - Placed corresponding sell order with ID: 1756776634666718976
2024-08-20 21:21:37,672 - INFO - Logged filled sell order to database
2024-08-20 21:21:37,672 - INFO - Done processing missed order updates
2024-08-20 21:21:37,898 - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-20 21:21:38,674 - INFO - Websocket connected
2024-08-20 21:21:38,674 - INFO - WebSocket Unified V5 (Auth) connected
2024-08-20 21:21:45,683 - INFO - Processing order with ID: 1756776726891075328, Status: New
2024-08-20 21:21:45,683 - INFO - Placed buy order at 60453.8, Order ID: 1756776726891075328
2024-08-20 21:22:00,262 - INFO - Processing order with ID: 1756776726891075328, Status: Filled
2024-08-20 21:22:00,264 - INFO - Order filled - ID: 1756776726891075328, Side: Buy, Price: 60453.8, Qty: 5e-05
2024-08-20 21:22:01,661 - INFO - Placed sell order at 60468.8, Order ID: 1756776854582466304
2024-08-20 21:22:02,282 - INFO - Placed corresponding sell order with ID: 1756776854582466304
2024-08-20 21:22:02,749 - INFO - Logged filled sell order to database
2024-08-20 21:22:02,750 - INFO - Processing order with ID: 1756776854582466304, Status: New
2024-08-20 21:22:08,469 - INFO - Shutting down gracefully...
2024-08-20 21:22:08,473 - INFO - State checkpointed successfully.
2024-08-20 21:22:08,475 - INFO - Flushed pending updates to CSV.
2024-08-20 21:22:08,695 - INFO - WebSocket connection closed.
